export const AIRTABLE_COLORS: Record<string, { bg: string; text: string }> = {
  blueBright:    { bg: '#166ee1', text: '#fff' },
  blueLight1:    { bg: '#a0c6ff', text: '#172b4d' },
  blueLight2:    { bg: '#d1e2ff', text: '#172b4d' },
  blueDark1:     { bg: '#0d52ac', text: '#fff' },
  cyanBright:    { bg: '#00b1e4', text: '#fff' },
  cyanLight1:    { bg: '#77d1f3', text: '#172b4d' },
  cyanLight2:    { bg: '#c2eefe', text: '#172b4d' },
  cyanDark1:     { bg: '#0070a3', text: '#fff' },
  tealBright:    { bg: '#02a59b', text: '#fff' },
  tealLight1:    { bg: '#72cac9', text: '#172b4d' },
  tealLight2:    { bg: '#c2eae9', text: '#172b4d' },
  tealDark1:     { bg: '#047a73', text: '#fff' },
  greenBright:   { bg: '#20a757', text: '#fff' },
  greenLight1:   { bg: '#93d98c', text: '#172b4d' },
  greenLight2:   { bg: '#cfedcc', text: '#172b4d' },
  greenDark1:    { bg: '#1a7f41', text: '#fff' },
  yellowBright:  { bg: '#fcb400', text: '#172b4d' },
  yellowLight1:  { bg: '#fed550', text: '#172b4d' },
  yellowLight2:  { bg: '#ffeab6', text: '#172b4d' },
  yellowDark1:   { bg: '#b27600', text: '#fff' },
  orangeBright:  { bg: '#ff6f2c', text: '#fff' },
  orangeLight1:  { bg: '#ffa981', text: '#172b4d' },
  orangeLight2:  { bg: '#fee2d5', text: '#172b4d' },
  orangeDark1:   { bg: '#d74d26', text: '#fff' },
  redBright:     { bg: '#f82b60', text: '#fff' },
  redLight1:     { bg: '#ff9eb9', text: '#172b4d' },
  redLight2:     { bg: '#ffdce5', text: '#172b4d' },
  redDark1:      { bg: '#ba1e45', text: '#fff' },
  pinkBright:    { bg: '#ff08c2', text: '#fff' },
  pinkLight1:    { bg: '#f99de2', text: '#172b4d' },
  pinkLight2:    { bg: '#fcdaf5', text: '#172b4d' },
  pinkDark1:     { bg: '#b2158b', text: '#fff' },
  purpleBright:  { bg: '#8b46ff', text: '#fff' },
  purpleLight1:  { bg: '#cdb0ff', text: '#172b4d' },
  purpleLight2:  { bg: '#ede2fe', text: '#172b4d' },
  purpleDark1:   { bg: '#6b1fb1', text: '#fff' },
  grayBright:    { bg: '#666583', text: '#fff' },
  grayLight1:    { bg: '#c9c7c0', text: '#172b4d' },
  grayLight2:    { bg: '#e9e9e7', text: '#172b4d' },
  grayDark1:     { bg: '#4e4d5e', text: '#fff' },
};

export function tagColorStyle(colorName: string | null): { background: string; color: string } {
  const c = colorName ? (AIRTABLE_COLORS[colorName] ?? null) : null;
  return c ? { background: c.bg, color: c.text } : { background: '#e4e7eb', color: '#5e6c84' };
}
